// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xwAq6O4cooB-cHrxraZOlL9RSg6IXHc',
    appId: '1:346321252307:web:04d5be034393d1d8814926',
    messagingSenderId: '346321252307',
    projectId: 'catalogo-peliculas-42ef5',
    authDomain: 'catalogo-peliculas-42ef5.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-42ef5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuzCkjJ724cIB4AVUltmb18VGFrKsRS0',
    appId: '1:346321252307:android:4690a132b0c532f4814926',
    messagingSenderId: '346321252307',
    projectId: 'catalogo-peliculas-42ef5',
    storageBucket: 'catalogo-peliculas-42ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3OO1XJx-m7g4m-sHDkfEmeWEQACb704Y',
    appId: '1:346321252307:ios:4dc902d7a3b91e34814926',
    messagingSenderId: '346321252307',
    projectId: 'catalogo-peliculas-42ef5',
    storageBucket: 'catalogo-peliculas-42ef5.firebasestorage.app',
    iosBundleId: 'com.example.integracionBaseDeDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3OO1XJx-m7g4m-sHDkfEmeWEQACb704Y',
    appId: '1:346321252307:ios:4dc902d7a3b91e34814926',
    messagingSenderId: '346321252307',
    projectId: 'catalogo-peliculas-42ef5',
    storageBucket: 'catalogo-peliculas-42ef5.firebasestorage.app',
    iosBundleId: 'com.example.integracionBaseDeDatos',
  );
}
